Try using travis' saucelabs connect file

diff --git a/scripts/travis_saucelabs b/scripts/travis_saucelabs
--- a/scripts/travis_saucelabs
+++ b/scripts/travis_saucelabs
@@ -1,20 +1,97 @@
 #!/bin/bash
 
-set -e # exit on error
+# So that we don't have to run saucelabs on every run, we manually use the
+# travis code - downloaded from:
+#
+# https://raw.githubusercontent.com/travis-ci/travis-build/master/lib/travis/build/addons/sauce_connect/templates/sauce_connect.sh
 
-# Setup and start Sauce Connect for your TravisCI build
-# This script requires your .travis.yml to include the following two private env variables:
-# SAUCELABS_USERNAME
-# SAUCELABS_API_KEY
+export _SC_PID=unset
 
-mkdir -p ~/saucelabs/sauce-connect
-cd ~/saucelabs
-wget https://saucelabs.com/downloads/sc-4.3.13-linux.tar.gz
-tar -xzvf sc-4.3.13-linux.tar.gz --strip-components 1 --directory sauce-connect
+function travis_start_sauce_connect() {
+  if [ -z "${SAUCE_USERNAME}" ] || [ -z "${SAUCE_ACCESS_KEY}" ]; then
+      echo "This script can't run without your Sauce credentials"
+      echo "Please set SAUCE_USERNAME and SAUCE_ACCESS_KEY env variables"
+      echo "export SAUCE_USERNAME=ur-username"
+      echo "export SAUCE_ACCESS_KEY=ur-access-key"
+      return 1
+  fi
 
-sauce-connect/bin/sc --readyfile ~/saucelabs/sauce-connect-ready -u $SAUCELABS_USERNAME -k $SAUCELABS_API_KEY &
+  local sc_tmp sc_platform sc_distro sc_distro_fmt sc_distro_shasum \
+    sc_readyfile sc_logfile sc_dir sc_tunnel_id_arg sc_actual_shasum
 
-# Wait for Sauce Connect to be ready before exiting
-while [ ! -f ~/saucelabs/sauce-connect-ready ]; do
+  sc_tmp="$(mktemp -d -t sc.XXXX)"
+  echo "Using temp dir $sc_tmp"
+  pushd $sc_tmp
+
+  sc_platform=$(uname | sed -e 's/Darwin/osx/' -e 's/Linux/linux/')
+  case "${sc_platform}" in
+      linux)
+          sc_distro_fmt=tar.gz
+          sc_distro_shasum=26d1f454864de104cac04afa457eddf510c642a2;;
+      osx)
+          sc_distro_fmt=zip
+          sc_distro_shasum=d29ce847880ece5ea8c7cfa94b0c89de5a4f328c;;
+  esac
+  sc_distro=sc-4.3.13-${sc_platform}.${sc_distro_fmt}
+  sc_readyfile=sauce-connect-ready-$RANDOM
+  sc_logfile=$HOME/sauce-connect.log
+  if [ ! -z "${TRAVIS_JOB_NUMBER}" ]; then
+    sc_tunnel_id_arg="-i ${TRAVIS_JOB_NUMBER}"
+  fi
+  echo "Downloading Sauce Connect"
+  wget http://saucelabs.com/downloads/${sc_distro}
+  sc_actual_shasum="$(openssl sha1 ${sc_distro} | cut -d' ' -f2)"
+  if [[ "$sc_actual_shasum" != "$sc_distro_shasum" ]]; then
+      echo "SHA1 sum of Sauce Connect file didn't match!"
+      return 1
+  fi
+  sc_dir=$(tar -ztf ${sc_distro} | head -n1)
+
+  echo "Extracting Sauce Connect"
+  case "${sc_distro_fmt}" in
+      tar.gz)
+          tar zxf $sc_distro;;
+      zip)
+          unzip $sc_distro;;
+  esac
+
+  ${sc_dir}/bin/sc \
+    ${sc_tunnel_id_arg} \
+    -f ${sc_readyfile} \
+    -l ${sc_logfile} \
+    ${SAUCE_NO_SSL_BUMP_DOMAINS} \
+    ${SAUCE_DIRECT_DOMAINS} \
+    ${SAUCE_TUNNEL_DOMAINS} &
+  _SC_PID="$!"
+
+  echo "Waiting for Sauce Connect readyfile"
+  while [ ! -f ${sc_readyfile} ]; do
     sleep .5
-done
+  done
+
+  popd
+}
+
+function travis_stop_sauce_connect() {
+  if [[ ${_SC_PID} = unset ]] ; then
+    echo "No running Sauce Connect tunnel found"
+    return 1
+  fi
+
+  kill ${_SC_PID}
+
+  for i in 0 1 2 3 4 5 6 7 8 9 ; do
+    if kill -0 ${_SC_PID} &>/dev/null ; then
+      echo "Waiting for graceful Sauce Connect shutdown"
+      sleep 1
+    else
+      echo "Sauce Connect shutdown complete"
+      return 0
+    fi
+  done
+
+  if kill -0 ${_SC_PID} &>/dev/null ; then
+    echo "Forcefully terminating Sauce Connect"
+    kill -9 ${_SC_PID} &>/dev/null || true
+  fi
+}
